sudo: required
services:
  - docker


before_install:
  - docker build -t roshvi/gitdocker  -f Dockerfile.dev .

script:
  - docker run roshvi/gitdocker npm run test -- -- coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockergit"
  env: "Dockergit-env"
  bucket_name: "elasticbeanstalk-us-east-2-655508036345"
  bucket_path: "dockergit"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_key:
    secure: "$AWS_SECRET_KEY"
